### PR TITLE
pls merge

### PR DESCRIPTION
**Pull request by raji2004**

### CODE REVIEW

**Comment by raji2004** [comment]
done please erge

**Comment by Sanket2055** [comment]
@raji2004   add info about  endpoints

**Comment by raji2004** [comment]
Ok

**Comment by raji2004** [comment]
pls merge

**Comment by Sanket2055** [comment]
> pls merge

hey @raji2004 its still incomplete , there are more than 10 endpoints . u have added only 4.

**Comment by raji2004** [comment]
u want me to add all the end points?

**Comment by Sanket2055** [comment]
> u want me to add all the end points?

yes , it should not take more than 15 mins . U just need to mention the endpoints and categorize them as  u did in the previous commit .

**Comment by raji2004** [comment]
> > u want me to add all the end points?
> 
> yes , it should not take more than 15 mins . U just need to mention the endpoints and categorize them as u did in the previous commit .

alright im on it

**Comment by raji2004** [comment]
done

**Comment by Sanket2055** [comment]
@raji2004 good work

**Pull request merged**
